### ISSUE TITLE
arch.py

### ISSUE THREAD

**Issue by LLL12312** [HaixiaBi1982/ActSemiCNNAct#2]
Excuse me, I got this error when running your code: ModuleNotFoundError: No module named 'architectures.arch', did you forget the arch.py file when you uploaded the code?

**Comment by HaixiaBi1982** [comment]
Uploaded

**Comment by LLL12312** [comment]
Excuse me, the 'architectures.lenet', 'architectures.vgg', 'architectures.resnet', 'architectures.preact_resnet' ,‘architectures.densenet’，‘architectures.resnext’，‘architectures.senet’，‘architectures.dpn’，‘architectures.shufflenet’，‘architectures.mobilenet’，‘architectures.mobilenetv2’，‘architectures.convlarge’，used in the arch.py file you uploaded,I did not find the relevant files in your code.

**Comment by HaixiaBi1982** [comment]
update arch.py
